### PR TITLE
Refactor of the bray curtis notebook

### PR DESCRIPTION
**Pull request by wasade**
Please note the TODOs; I do not think this is ready for merge until at a minimum they are resolved. I'm hoping to avoid going into detail on the studies and just provide hyperlinks to Qiita but can add if others would like.

### CODE REVIEW

**Comment by jwdebelius** [comment]
In the _Join all data into a single table and dataframe_ cell:

``` python
assert set(table.ids()).issubset(metadata.index)
assert len(table.ids()) == len(metadata)
```

Could this be simplified to

``` python
assert set(table.ids()) == set(metadata.index)
```

**Comment by jwdebelius** [comment]
I'm a little bit unclear on the goal of the sample and replace function, compared to other approaches, like using `np.random.choice` and filtering. Is that more expensive?

@amnona and/or @mortonjt should also review

**Comment by wasade** [comment]
Thanks, Justine. It's not a performance thing, it was that the sample IDs
were already stored in dataframes so it was easiest to just use the
dataframe API. Even with `np.random.choice`, we'd still need to map an ID
to an index. I'm open to alternative approaches here though.

**Comment by wasade** [comment]
@jwdebelius good call on not needing the length check. A duplicate in `index` isn't allowed, and a duplicate in `Table` isn't allowed.

**Comment by jwdebelius** [comment]
Actually, you can have duplicates in `index`.  Not here, but in general, you can. So, the other was likely smarter.

**Comment by wasade** [comment]
Huh... well, I already made the change and even if a dup slipped into index i dont think it would have any actual impact

**Comment by amnona** [comment]
QiitaIDs for the studies:
pgp - 1189
whole grain feces - 1481
uk twins - 2014

**Comment by amnona** [comment]
look good :)
in general, maybe instead of first making the new NUMITERATION sized matrices for each experiment and then calculating bray curtis on them, we can take each time one sample from each experiment and just add the bray-curtis distance (more efficient memory-wise)
but not critical - it works also like this...

**Comment by amnona** [comment]
👍

**Comment by jwdebelius** [comment]
👍 , but Amnon needs to merge.

**Comment by wasade** [comment]
please do not merge yet. tidying up.

**Comment by wasade** [comment]
@amnona, its just a few megabytes. There is a logical separation, or rather, a separation of concerns, between the generation of the data and its summarization. If we decide to change how we're summarizing (e.g., medians), we do not need to touch the logic which generates the data. Since we aren't in a position where things are prohibitively slow (it takes about 3 minutes to run the full notebook) or memory intensive (it takes about 1.2GB of memory for the full notebook), I'd argue that maintaining this separation is better.

**Comment by wasade** [comment]
Okay, ready for final review.

Please note: I renamed files.

**Comment by amnona** [comment]
👍

**Comment by wasade** [comment]
@amnona I believe you're the only one with merge since this is to your branch/repo

**Pull request merged**
